before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    binary: machina
    id: machina
    env:
      - CGO_ENABLED=0
      - GITHUB_TOKEN="test"
    goarch:
    - amd64
    ldflags:
    - -s
    - -w
    - -X github.com/enkodr/machina/cmd.version={{.Version}}
    - -X github.com/enkodr/machina/cmd.gitCommit={{.Commit}}
    - -X github.com/enkodr/machina/cmd.buildDate={{.Date}}
    goos:
      - linux
archives:
  - id: machina
    builds: 
    - machina
    format: binary
checksum:
  algorithm: sha256
