name: release

on:
  push:
    tags:
    - "v*"

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  
  release:
    needs: [test]
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"

    - name: Run GoRelease
      uses: goreleaser/goreleaser-action@v5
      with:
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
